version: '3.8'

services:
  # 聊天室应用
  chatroom:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MODE=release
      - JWT_SECRET=your-super-secret-jwt-key
      - REDIS_ADDR=redis:6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_CONNECTION_STRING=root:password@tcp(mysql:3306)/chatroom?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
      - redis
      - kafka
    restart: unless-stopped

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chatroom
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Zookeeper (Kafka 依赖)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    restart: unless-stopped

  # Kafka 消息队列
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  kafka_data: